global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'streamflow-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'event-producer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # Docker container (port 8080) + IntelliJ local dev (port 8083)
      - targets: ['event-producer-service:8080']
        labels:
          instance: 'docker'
      - targets: ['host.docker.internal:8083']
        labels:
          instance: 'intellij-local'
    scrape_interval: 10s

  - job_name: 'stream-processor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['stream-processor-service:8081']
    scrape_interval: 10s

  - job_name: 'analytics-api-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-api-service:8082']
    scrape_interval: 10s
