package com.streamflow.producer.service;

import com.streamflow.producer.model.enums.EventType;
import com.streamflow.producer.model.event.UserEvent;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.List;
import java.util.Random;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Realistic e-commerce load simulator.
 * Active only when streamflow.producer.auto-generate-events=true.
 *
 * <p>Simulates a realistic user funnel:
 * CLICK (50%) → ADD_TO_CART (25%) → PURCHASE (10%) → EXIT (15%)</p>
 */
@Slf4j
@Component
@EnableScheduling
@ConditionalOnProperty(name = "streamflow.producer.auto-generate-events", havingValue = "true")
public class LoadSimulator {

    private static final int  PRODUCT_COUNT  = 20;
    private static final int  USER_COUNT     = 50;
    private static final int  SESSION_COUNT  = 30;

    // Weighted event distribution: realistic funnel
    private static final List<EventType> EVENT_POOL = List.of(
            EventType.CLICK,       EventType.CLICK,       EventType.CLICK,
            EventType.CLICK,       EventType.CLICK,       // 5 CLICK  (50%)
            EventType.ADD_TO_CART, EventType.ADD_TO_CART, EventType.ADD_TO_CART, // 3 ADD (30%)
            EventType.PURCHASE,                            // 1 PURCHASE (10%)
            EventType.EXIT                                 // 1 EXIT (10%)
    );

    private final EventPublisher  eventPublisher;
    private final int             eventsPerBatch;
    private final Counter         simulatedCounter;

    public LoadSimulator(
            EventPublisher eventPublisher,
            @Value("${streamflow.producer.events-per-second:5}") int eventsPerBatch,
            MeterRegistry meterRegistry) {
        this.eventPublisher   = eventPublisher;
        this.eventsPerBatch   = eventsPerBatch;
        this.simulatedCounter = Counter.builder("streamflow.simulated.events.total")
                .description("Total events generated by load simulator")
                .register(meterRegistry);
    }

    /**
     * Fires every 2 seconds, generates a small burst of events.
     * Rate = eventsPerBatch / 2s → roughly eventsPerBatch/2 events per second.
     */
    @Scheduled(fixedRateString = "${streamflow.producer.simulator-interval-ms:2000}")
    public void generateEvents() {
        ThreadLocalRandom rnd = ThreadLocalRandom.current();

        for (int i = 0; i < eventsPerBatch; i++) {
            long     userId    = rnd.nextLong(1, USER_COUNT + 1);
            long     productId = rnd.nextLong(1, PRODUCT_COUNT + 1);
            String   sessionId = "sim-session-" + rnd.nextLong(1, SESSION_COUNT + 1);
            EventType eventType = EVENT_POOL.get(rnd.nextInt(EVENT_POOL.size()));

            // Occasionally simulate a late event (5% chance, up to 2 min late)
            Instant eventTime = rnd.nextDouble() < 0.05
                    ? Instant.now().minusSeconds(rnd.nextLong(30, 120))
                    : Instant.now();

            UserEvent event = UserEvent.builder()
                    .eventId(UUID.randomUUID().toString())
                    .userId(userId)
                    .sessionId(sessionId)
                    .eventType(eventType)
                    .productId(productId)
                    .price(roundPrice(rnd.nextDouble(5.0, 500.0)))
                    .eventTime(eventTime)
                    .build();

            eventPublisher.publish(event);
            simulatedCounter.increment();
        }

        log.debug("Simulator batch: {} events generated", eventsPerBatch);
    }

    private double roundPrice(double price) {
        return Math.round(price * 100.0) / 100.0;
    }
}
